const gameBoard = document.querySelector("#board");
const ctx = gameBoard.getContext("2d");
const scoreText = document.querySelector("#score");
const resetBtn = document.querySelector("#reset");
const gameWidth = gameBoard.width;
const gameHeight = gameBoard.height;
const boardBackground = "orange";
const paddle1Color = "black";
const paddle2Color = "white";
const paddleBorder = "black";
const ballColor = "yellow";
const ballBorderColor;